const questionsWithImage = [
  {
    questionText:
      "Quale attributo HTML è usato per definire **il percorso di un'immagine**?",
    imageUrl: 'https://placecats.com/millie/300/150',
    answers: [
      { text: 'src', isCorrect: true, score: 1 },
      { text: 'href', isCorrect: false, score: 0 },
      { text: 'path', isCorrect: false, score: 0 },
      { text: 'link', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText: 'Quale tag HTML è usato per **creare una tabella**?',
    imageUrl: 'https://placecats.com/millie_neo/300/200',
    answers: [
      { text: '<table>', isCorrect: true, score: 1 },
      { text: '<grid>', isCorrect: false, score: 0 },
      { text: '<tbl>', isCorrect: false, score: 0 },
      { text: '<tab>', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Come si aggiunge **una classe** a un elemento in JavaScript?',
    imageUrl: '',
    answers: [
      {
        text: "element.classList.add('nomeClasse')",
        isCorrect: true,
        score: 1,
      },
      { text: "element.className += 'nomeClasse'", isCorrect: false, score: 0 },
      { text: "element.addClass('nomeClasse')", isCorrect: false, score: 0 },
      { text: "element.class = 'nomeClasse'", isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quale proprietà CSS è usata per modificare **il colore del testo**?',
    imageUrl: '',
    answers: [
      { text: 'color', isCorrect: true, score: 1 },
      { text: 'text-color', isCorrect: false, score: 0 },
      { text: 'font-color', isCorrect: false, score: 0 },
      { text: 'background-color', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quale di questi selettori CSS è usato per selezionare **un elemento con un id specifico**?',
    imageUrl: 'https://placecats.com/neo_banana/300/200',
    answers: [
      { text: '#', isCorrect: true, score: 1 },
      { text: '.', isCorrect: false, score: 0 },
      { text: '*', isCorrect: false, score: 0 },
      { text: '::', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quale metodo JavaScript viene utilizzato per **stampare messaggi nella console**?',
    imageUrl: 'https://placecats.com/neo_2/300/200',
    answers: [
      { text: 'console.log()', isCorrect: true, score: 1 },
      { text: 'print()', isCorrect: false, score: 0 },
      { text: 'echo()', isCorrect: false, score: 0 },
      { text: 'write()', isCorrect: false, score: 0 },
    ],
  },
  {
    questionText:
      "Quale tag HTML viene utilizzato per **inserire un'immagine**?",
    imageUrl: 'https://placecats.com/bella/300/200',
    answers: [
      { text: '<img>', isCorrect: true, score: 1 },
      { text: '<image>', isCorrect: false, score: 0 },
      { text: '<pic>', isCorrect: false, score: 0 },
      { text: '<src>', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quale proprietà CSS è utilizzata per modificare **la dimensione del testo**?',
    imageUrl: '',
    answers: [
      { text: 'font-size', isCorrect: true, score: 1 },
      { text: 'text-size', isCorrect: false, score: 0 },
      { text: 'size', isCorrect: false, score: 0 },
      { text: 'font', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText: 'Quale tag HTML definisce **una intestazione**?',
    imageUrl: 'https://placecats.com/millie/300/150',
    answers: [
      { text: '<h1>', isCorrect: true, score: 1 },
      { text: '<header>', isCorrect: false, score: 0 },
      { text: '<head>', isCorrect: false, score: 0 },
      { text: '<title>', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText: 'Come si definisce **un commento** in JavaScript?',
    imageUrl: '',
    answers: [
      { text: '// Questo è un commento', isCorrect: true, score: 1 },
      { text: '# Questo è un commento', isCorrect: false, score: 0 },
      { text: '/* Questo è un commento */', isCorrect: false, score: 0 },
      { text: '<!-- Questo è un commento -->', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quale proprietà CSS permette di rendere **un testo in grassetto**?',
    imageUrl: 'https://placecats.com/millie_neo/300/200',
    answers: [
      { text: 'font-weight', isCorrect: true, score: 1 },
      { text: 'font-style', isCorrect: false, score: 0 },
      { text: 'text-weight', isCorrect: false, score: 0 },
      { text: 'bold', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      "Quale evento JavaScript viene attivato **quando l'utente invia un form**?",
    imageUrl: '',
    answers: [
      { text: 'submit', isCorrect: true, score: 1 },
      { text: 'send', isCorrect: false, score: 0 },
      { text: 'load', isCorrect: false, score: 0 },
      { text: 'post', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText: 'Quale tag HTML è usato per **creare un elenco numerato**?',
    imageUrl: 'https://placecats.com/neo_banana/300/200',
    answers: [
      { text: '<ol>', isCorrect: true, score: 1 },
      { text: '<ul>', isCorrect: false, score: 0 },
      { text: '<li>', isCorrect: false, score: 0 },
      { text: '<list>', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      "Quale attributo HTML viene utilizzato per associare **un'etichetta a un elemento del form**?",
    imageUrl: '',
    answers: [
      { text: 'for', isCorrect: true, score: 1 },
      { text: 'id', isCorrect: false, score: 0 },
      { text: 'name', isCorrect: false, score: 0 },
      { text: 'label', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      "Quale metodo JavaScript viene usato per **rimuovere l'ultimo elemento di un array**?",
    imageUrl: '',
    answers: [
      { text: 'pop()', isCorrect: true, score: 1 },
      { text: 'shift()', isCorrect: false, score: 0 },
      { text: 'remove()', isCorrect: false, score: 0 },
      { text: 'splice()', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText: 'Come si specifica **un font** in CSS?',
    imageUrl: '',
    answers: [
      { text: 'font-family', isCorrect: true, score: 1 },
      { text: 'font-style', isCorrect: false, score: 0 },
      { text: 'font-weight', isCorrect: false, score: 0 },
      { text: 'text-font', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quale dei seguenti selettori CSS viene utilizzato **per selezionare tutti gli elementi**?',
    imageUrl: 'https://placecats.com/neo_2/300/200',
    answers: [
      { text: '*', isCorrect: true, score: 1 },
      { text: '#', isCorrect: false, score: 0 },
      { text: '.', isCorrect: false, score: 0 },
      { text: '::', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText: 'Come si dichiara **una variabile costante** in JavaScript?',
    imageUrl: 'https://placecats.com/bella/300/200',
    answers: [
      { text: 'const', isCorrect: true, score: 1 },
      { text: 'var', isCorrect: false, score: 0 },
      { text: 'let', isCorrect: false, score: 0 },
      { text: 'constant', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      "Quale metodo JavaScript è utilizzato **per aggiungere un nuovo elemento all'inizio di un array**?",
    imageUrl: '',
    answers: [
      { text: 'unshift()', isCorrect: true, score: 1 },
      { text: 'push()', isCorrect: false, score: 0 },
      { text: 'pop()', isCorrect: false, score: 0 },
      { text: 'shift()', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quale tag HTML si utilizza **per creare un link ipertestuale**?',
    imageUrl: 'https://placecats.com/millie/300/150',
    answers: [
      { text: '<link>', isCorrect: false, score: 0 },
      { text: '<a>', isCorrect: true, score: 1 },
      { text: '<href>', isCorrect: false, score: 0 },
      { text: '<url>', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quali di questi tag HTML sono validi **per la formattazione del testo**?',
    imageUrl: 'https://placecats.com/millie_neo/300/200',
    answers: [
      { text: '<b>', isCorrect: true, score: 1 },
      { text: '<i>', isCorrect: true, score: 1 },
      { text: '<span>', isCorrect: true, score: 1 },
      { text: '<font>', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quali attributi si possono utilizzare **per un tag <input> in un form HTML**?',
    imageUrl: '',
    answers: [
      { text: 'type', isCorrect: true, score: 1 },
      { text: 'placeholder', isCorrect: true, score: 1 },
      { text: 'method', isCorrect: false, score: 0 },
      { text: 'required', isCorrect: true, score: 1 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quali metodi JavaScript si possono usare **per selezionare elementi dal DOM**?',
    imageUrl: 'https://placecats.com/neo_banana/300/200',
    answers: [
      { text: 'getElementById', isCorrect: true, score: 1 },
      { text: 'getElementsByClassName', isCorrect: true, score: 1 },
      { text: 'querySelector', isCorrect: true, score: 1 },
      { text: 'getClass', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText: 'Quali dei seguenti elementi sono **semantici in HTML5**?',
    imageUrl: 'https://placecats.com/neo_2/300/200',
    answers: [
      { text: '<header>', isCorrect: true, score: 1 },
      { text: '<footer>', isCorrect: true, score: 1 },
      { text: '<div>', isCorrect: false, score: 0 },
      { text: '<article>', isCorrect: true, score: 1 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quali tecniche CSS possono essere usate **per posizionare un elemento al centro di una pagina**?',
    imageUrl: '',
    answers: [
      { text: 'flexbox', isCorrect: true, score: 1 },
      { text: 'grid', isCorrect: true, score: 1 },
      { text: 'float', isCorrect: false, score: 0 },
      {
        text: 'position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);',
        isCorrect: true,
        score: 1,
      },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quali degli operatori seguenti in JavaScript sono utilizzati **per confrontare valori**?',
    imageUrl: '',
    answers: [
      { text: '==', isCorrect: true, score: 1 },
      { text: '===', isCorrect: true, score: 1 },
      { text: '!=', isCorrect: true, score: 1 },
      { text: '&&', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quali delle seguenti sono tecniche **per ottimizzare il caricamento di una pagina web**?',
    imageUrl: 'https://placecats.com/bella/300/200',
    answers: [
      { text: 'Minificare file CSS e JavaScript', isCorrect: true, score: 1 },
      {
        text: 'Usare il lazy loading per le immagini',
        isCorrect: true,
        score: 1,
      },
      { text: 'Utilizzare solo immagini SVG', isCorrect: false, score: 0 },
      {
        text: 'Ridurre il numero di richieste HTTP',
        isCorrect: true,
        score: 1,
      },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quali eventi JavaScript possono essere utilizzati **per rilevare interazioni con un utente**?',
    imageUrl: '',
    answers: [
      { text: 'click', isCorrect: true, score: 1 },
      { text: 'mouseover', isCorrect: true, score: 1 },
      { text: 'load', isCorrect: false, score: 0 },
      { text: 'keydown', isCorrect: true, score: 1 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quali di queste dichiarazioni JavaScript possono **bloccare il flusso del codice**?',
    imageUrl: 'https://placecats.com/millie/300/150',
    answers: [
      { text: 'if', isCorrect: true, score: 1 },
      { text: 'while', isCorrect: true, score: 1 },
      { text: 'for', isCorrect: true, score: 1 },
      { text: 'switch', isCorrect: true, score: 1 },
    ],
    difficulty: 1,
    topic: 'HTML, CSS, JS',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      "Qual è l'ingrediente principale **per fare una pizza Margherita tradizionale**?",
    imageUrl:
      'https://thumbs.dreamstime.com/z/fresh-ripe-organic-red-tomatoes-hot-chili-peppers-arranged-brown-mexican-italian-spanish-greek-mediterranean-cuisine-fresh-ripe-120260617.jpg?ct=jpeg',
    answers: [
      { text: 'Pomodoro', isCorrect: true, score: 1 },
      { text: 'Mozzarella di bufala', isCorrect: true, score: 1 },
      { text: 'Basilico', isCorrect: false, score: 0 },
      { text: 'Parmigiano', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'Cucina',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Qual è la temperatura ideale **per cucinare una bistecca alla griglia**?',
    imageUrl:
      'https://thumbs.dreamstime.com/z/filet-mignon-tender-lean-cut-beef-tenderloin-grilled-generative-ai-filet-mignon-tender-lean-cut-beef-324118221.jpg?ct=jpeg',
    answers: [
      { text: '200°C', isCorrect: true, score: 1 },
      { text: '150°C', isCorrect: false, score: 0 },
      { text: '100°C', isCorrect: false, score: 0 },
      { text: '250°C', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'Cucina',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      "Qual è l'ingrediente chiave **per ottenere un soufflé perfetto**?",
    imageUrl:
      'https://thumbs.dreamstime.com/z/two-portion-cheese-suffle-29937183.jpg?ct=jpeg',
    answers: [
      { text: 'Albumi montati a neve', isCorrect: true, score: 1 },
      { text: 'Farina', isCorrect: false, score: 0 },
      { text: 'Latte', isCorrect: false, score: 0 },
      { text: 'Zucchero', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'Cucina',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText: 'Qual è il metodo corretto **per sfilettare un pesce**?',
    imageUrl:
      'https://thumbs.dreamstime.com/z/italy-venice-fish-market-4149517.jpg?ct=jpeg',
    answers: [
      {
        text: 'Usare un coltello affilato e seguire la spina dorsale',
        isCorrect: true,
        score: 1,
      },
      { text: 'Tagliare il pesce a metà', isCorrect: false, score: 0 },
      { text: 'Usare una forchetta', isCorrect: false, score: 0 },
      { text: 'Cuocere il pesce prima', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'Cucina',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Qual è il tempo di cottura **ideale per una pasta al dente**?',
    imageUrl:
      'https://thumbs.dreamstime.com/z/pasta-spaghetti-bolognese-white-plate-kitchen-towel-over-white-marble-table-healthy-food-top-view-pasta-spaghetti-121471552.jpg?ct=jpeg',
    answers: [
      { text: '7-9 minuti', isCorrect: true, score: 1 },
      { text: '10-12 minuti', isCorrect: false, score: 0 },
      { text: '5-6 minuti', isCorrect: false, score: 0 },
      { text: '13-15 minuti', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'Cucina',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Quali spezie sono essenziali **per preparare un curry tradizionale**?',
    imageUrl:
      'https://thumbs.dreamstime.com/z/curry-powder-12459865.jpg?ct=jpeg',
    answers: [
      { text: 'Curcuma, cumino, coriandolo', isCorrect: true, score: 1 },
      { text: 'Pepe nero, cannella, zafferano', isCorrect: false, score: 0 },
      { text: 'Rosmarino, salvia, alloro', isCorrect: false, score: 0 },
      { text: 'Timo, maggiorana, prezzemolo', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'Cucina',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Cosa è importante **quando si prepara una maionese fatta in casa**?',
    imageUrl:
      'https://thumbs.dreamstime.com/z/mayonnaise-sauce-fresh-tasty-bowl-rustic-wooden-background-close-up-horizontal-67832791.jpg?ct=jpeg',
    answers: [
      { text: "Aggiungere l'olio lentamente", isCorrect: true, score: 1 },
      { text: "Usare solo olio d'oliva", isCorrect: false, score: 0 },
      { text: 'Mescolare rapidamente', isCorrect: false, score: 0 },
      { text: "Aggiungere l'acqua all'inizio", isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'Cucina',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Qual è il taglio di carne migliore **per preparare un arrosto perfetto**?',
    imageUrl:
      'https://thumbs.dreamstime.com/z/roasted-meat-bay-leaf-baked-186503126.jpg?ct=jpeg',
    answers: [
      { text: 'Controfiletto', isCorrect: true, score: 1 },
      { text: 'Pancetta', isCorrect: false, score: 0 },
      { text: 'Petto di pollo', isCorrect: false, score: 0 },
      { text: 'Braciole di maiale', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'Cucina',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Qual è il metodo migliore **per mantenere croccanti le patatine fritte**?',
    imageUrl:
      'https://thumbs.dreamstime.com/z/patatine-fritte-frenchfries-contorno-frittura-157025596.jpg?ct=jpeg',
    answers: [
      { text: 'Cuocerle due volte', isCorrect: true, score: 1 },
      { text: 'Salarle prima della cottura', isCorrect: false, score: 0 },
      { text: 'Cuocerle a fuoco basso', isCorrect: false, score: 0 },
      { text: "Cuocerle con olio d'oliva", isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'Cucina',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
  {
    questionText:
      'Qual è la tecnica corretta **per preparare un risotto cremoso**?',
    imageUrl:
      'https://thumbs.dreamstime.com/z/comfort-food-ideas-scoop-creamy-rice-pudding-cozy-bowl-ideal-rainy-day-ultimate-317657642.jpg?ct=jpeg',
    answers: [
      { text: 'Aggiungere il brodo gradualmente', isCorrect: true, score: 1 },
      { text: 'Cuocerlo a fuoco alto', isCorrect: false, score: 0 },
      { text: 'Aggiungere la panna', isCorrect: false, score: 0 },
      { text: 'Cuocerlo in forno', isCorrect: false, score: 0 },
    ],
    difficulty: 1,
    topic: 'Cucina',
    time: 60,
    userAnswers: [],
    questionScore: 0,
  },
]
